### ISSUE TITLE
mount kill count after obtained

### ISSUE THREAD

**Issue by Voxxel** [SacredDuckwhale/Rarity#172]
Hi!

I use Rarity for years to track attempts. Now I finally received Astral Cloud Serpent from Elegon. A guildie asked how much I had to kill it before the mount dropped. I tried everything to gather kill count for Elegon from Rarity but I failed to do that.

Where can I find that information within the addon?

**Comment by SacredDuckwhale** [comment]
You can simply check your ingame statistics; they're provided by Blizzard in the second tab of the Achievements UI. Rarity uses those to track attempts so it would be the same count.

**Comment by Voxxel** [comment]
That was the first thing I did but the ingame stats gives me only 4 Elegon kills on each difficulties I don't know why. (I was farming this guy since Pandaria on my main character, and rarity already counted 1xx kills. 

But come on, the question was how could I print a kill count for a boss in Rarity that's already counted by the addon. Shouldn't be that hard.

It's a pretty basic task to get a kill count number from an addon that primarily created to collect kill count numbers, isn't it...

**Comment by SacredDuckwhale** [comment]
You can try opening the Options UI and check the number written under "Attempts" for the respective item, although it's really using the same statistics obtained from Blizzard's API.

This would only change the result if you've killed it on multiple characters and didn't count those manually, as Rarity accumulates statistics gathered from all characters you logged in on with the addon enabled.

If you still want to investigate further, you could open the SavedVariables and search for ``attempts`` under ``Reins of the Astral Cloud Serpent`` (it should be the exact same number), or manually count all instances of the respective statistics under ``accountWideStatistics`` (6797, 6798, 7924, 7923 is 10/25 normal and heroic Elegon, as listed on [wowhead](https://www.wowhead.com/search?q=elegon+kills)). This is all the addon does internally.

**Comment by Voxxel** [comment]
On every kill, a number printed out (by the addon) that counts how many I killed a particular boss. 
Why on Earth should it be so damn hard to check the last number it printed? 

Isn't this addon for counting kills primarily? Why should I dig through lua / savedvariable files? 
I just can't believe it. I use an addon for years to collect kill counts and the end I can't get the number of my attempts when the mount years later finally drops...

**Comment by SacredDuckwhale** [comment]
The easiest way to get the number *after the fact* is exactly as I wrote:

Press ESC, go to Interface > Addons > Rarity and then Mounts > Reins of the Astral Cloud Serpents. That's what I meant when I said "Options UI", and it's the simplest way to get the attempts count (far simpler than printing something in chat).

Naturally, the addon prints the attempt count after you kill the boss. That's what most people use it for, after all. But you've already got the mount and clearly didn't remember the number it printed, so now you wanted to check the last one the addon saved? That's what I understand you wanted to do, anyway.

The other options I gave were more advanced, in case this count isn't what you were referring to. There should be no need to dig around in SavedVariables/Lua files, but in case you wanted to I still added the instructions.

Another option I can think of is to simply check your Screenshots folder. Unless you changed it or deleted/cleared them at some point after getting the mount, Rarity would probably have made a screenshot when you actually obtained it, and that's where the attempt count is *also* written.

**Comment by Voxxel** [comment]
> Press ESC, go to Interface > Addons > Rarity and then Mounts > Reins of the Astral Cloud Serpents. That's what I meant when I said "Options UI", and it's the simplest way to get the attempts count (far simpler than printing something in chat).

I read that option in your second reply already but as you mentioned it reads kill count from the Blizzard API I thought you've understood that doesn't work for me (Blizzard statistics show only 4 kills for elegon in all difficulties, instead of hundred-some.)

By the way how come the Rarity's "Attempts" field shows "0" when the statistics say valid kills? This goes most of other items too. Their attempts are all "0".

https://i.imgur.com/a1kyhri.png

The screenshot was the 2nd thing I've checked but no success. That's probably why the kill count prints at the moment when Elegon dies and I have to walk to the coffer and open it to see if the mount is inside or not.

**Comment by SacredDuckwhale** [comment]
I'm not sure what you'd like for me to do about Blizzard's statistics being inaccurate. I have no control over them working or not, and unfortunately they've been broken by their patches many times in the past. There's no way for me to fix the problem you're describing, though you may want to report it as a bug ingame.

Indeed the reason for the attempts being printed before opening the box is because it's far easier (and usually, more reliable) to check for updated statistics than actually recognize the chest being opened. This again is due to the way Blizzard's API works and nothing I can really change.

As for the attempts count being "0", you'd have to ask the person who actually wrote the addon, which isn't me. Unfortunately they've stopped playing in Warlords of Draenor, so I can only give a best guess. I think you'd have to enable tracking for the item again (by checking "Repeatable" and "Track this") before the addon scans the statistics for a given item and updates the count.

**Comment by Voxxel** [comment]
I wouldn't like for you anything just had to tell you that your best guessed option (to check "Attempts" in Rarity) isn't a solution for me, because the blizzard statistics is screwed up. That's it.

For counts being "0" this is not only for the already acquired items/mounts/etc but those which already in progress too. It's also not only for the manually added items, but the rarity stock items too. On the other hands there are some already finished (acquired) items, that show the kill count correctly, like Xinlao, which I looted 2 days ago and it shows the correct attempt number correctly "12". I can't get which kind of pattern is behind this issue but frankly, I wouldn't care at all if as long I could read the kill numbers counted by Rarity *anytime* for the items included in the addon.

**Comment by SacredDuckwhale** [comment]
I mean, is your question answered? If there's something actionable here I'll do my best to help, but I unfortunately can't change the statistics count on Blizzard's servers.

The kill numbers recorded are exactly what you're reading, there's no secret data store that you can't access and Rarity doesn't hide the counter from you, as far as I know. If the addon displays a "0" then that's what it thinks the kill number is, which, naturally, may or may not be wrong.

If the actual issue now is that the attempts are wrong, then of course there may be many possible explanations for that. In order to see if there's a display bug I'd need to compare the attempts displayed in the UI with the count stored in your saved variables, but it's more likely the addon simply doesn't have any data for those items.

Generally speaking, items that don't use statistics need the addon to be enabled in order to be tracked and that data isn't persistent, so it may well be lost if you don't have a backup and the saved variables are deleted, or even just corrupted by the game client itself.

Those that do use statistics rely on Blizzard's API, so they should *usually* be counted correctly.

**Comment by Voxxel** [comment]
The actual issue here is about the title- I saw a kill count number on my screen printed by Rarity when I defeated Elegon and the mount dropped and I need to know that number. That's it, still.

I don't understand why do you say the addon just pulls the kill counts from wow statistics because I get quite different numbers for bosses. While rarity prints hundred-something-ish kills for e.g. Elegon upon defeating the boss the wow statistics are bugged and not showing the same amount of kills, not even close. This goes for other bosses too, while the statistics shows few kills for all difficulties, Rarity gives me seemingly the proper hundreds of kills.

**Comment by SacredDuckwhale** [comment]
Just to make sure I understand you correctly: Are you (and have you) killed it on one character or on multiple alts?

Rarity simply takes the statistics count whenever Blizzard provides one for a given boss, for all relevant difficulties if there are several, and finally sums them up for all characters that have logged in with the addon enabled. I believe this could cause issues if some characters were renamed or moved to another server, as the counts for the "old" characters would still be stored, but I'm not sure if that's a concern here.

This accumulated count is what should be displayed in the UI. If that isn't the case, it doesn't sound right and might indeed be a bug. It would print 100+ kills if, across all the characters that it knows, you have accumulated that many kills. One character would most likely have less than those unless you never killed it on any alts.

**Comment by Voxxel** [comment]
I killed it for years mostly on one character, few kills could be on alts too. But the main concern here is still not about the calculating of the kills or how the kills were distributed among the characters, etc.

I just saw rarity popped a kill number for a boss and I wish to know what number was it, using the addon in-game. I don't mind if it's a chat command or a button but I don't think digging through luas is the way-to-go for such a basic and foundational task.

**Comment by SacredDuckwhale** [comment]
I feel like I'm repeating myself, so I'll refrain from explaining once more how the attempts are calculated and why it's relevant to the statistics not being correct on Blizzard's end.

If you want me to help you, you can't just insist on things being too complicated after the most straight-forward way to retrieve your attempts count didn't yield the desired result. I'm using my free time to respond to your replies despite some of them being very... poorly worded (to say the least), as well as maintaining this addon for all to use, and I won't waste any more of my time if you can't accept that I don't have all the answers... Though even the addon's original author likely wouldn't be able to help in this case.

That said, this is what we can try:

1. If you enable tracking for the item again ('repeatable' + 'track this' checkboxes), then enter 0 in the attempts field and confirm it, Rarity will recalculate the attempts from all your character's statistics AFAIK. That number is what the addon thinks the total count is, based on all your character's statistics. Hopefully, this will be the number you're looking for.

2. There is no way to know for sure what number was originally printed when you got the mount unless you still have a screenshot/the addon's database (saved variables) that were in use at the time. If you didn't reset the settings since then, you can send them to me and I'll do the "digging through Lua files" part to see what numbers are stored in there, but that's the best I can offer you. There's no guarantee it would still hold the data, as it might've been overwritten by new (and incorrect, if bugged) statistics data later.

3. If you don't have the database from back in the day and/or Blizzard's statistics are wrong, the original count most likely can't be restored for all the reasons described, at length, in the previous answers. This has nothing to do with the addon itself, as it can only use the data that Blizzard's API makes available, which may or may not be wrong.

**Comment by Voxxel** [comment]
It's not about that I can't dig though code files, it's about a critical enhancement for the most basic task this addon aims to provide. It is also hard to understand (for me at least) how come an addon that made for counts kills can't _tell_ the counted kills. It's all self-contradictory...

I'm already dug out the kill count from the lua btw,
```
					`["Reins of the Astral Cloud Serpent"] = {
						["lastAttempts"] = 169,
						["known"] = true,
						["finds"] = {
							{
								["num"] = 1,
								["totalAttempts"] = 169,
								["time"] = 1,
								["totalTime"] = 1,
								["attempts"] = 169,
							}, -- [1]
						},
						["time"] = 1,
						["dates"] = {
							[20160721] = {
								["time"] = 1,
							},
						},
						["enabled"] = false,
						["attempts"] = 169,
						["realAttempts"] = 169,
						["totalFinds"] = 1,
						["found"] = true,
						["lastTime"] = 1,
					},`
```
but it should be indeed a simple way to read the kill counts through the addon in game.

**Comment by SacredDuckwhale** [comment]
You're right that adding this would be a logical feature for the addon to have, but I guess the original author didn't agree and so hasn't added it? Perhaps they figured seeing the attempts in the options UI would be enough. I've basically just been on maintenance duty and I've hardly had the time to tackle anything major like that.

Either way, I do think there could be a better UI and have already accepted a similar request in https://github.com/SacredDuckwhale/Rarity/issues/173. As such I'm going to close this issue and maybe when I have a lot of free time I can try to implement something that makes the process less painful.

**Comment by Voxxel** [comment]
Cool, thank you!
