### ISSUE TITLE
Cat Carrier (Black Tabby) is not tracked as a zone drop in Hillsbrad Foothills

### ISSUE THREAD

**Issue by astradamus** [SacredDuckwhale/Rarity#190]
https://www.wowhead.com/npc=7383/black-tabby-cat

My guess is that this was never updated when Black Tabby was moved to being a zone drop, as it used to be limited to specific mobs. This must have been recent, as the mod "All The Things" is also unaware of this drop .

In-game pet search:
![image](https://user-images.githubusercontent.com/12521094/89744395-460a8980-da61-11ea-99af-82a2165321c7.png)

Here it is incorrectly listed as limited to specific NPCs:

![image](https://user-images.githubusercontent.com/12521094/89744578-3724d680-da63-11ea-813c-dc4ed604cdc4.png)

I can't figure out how to edit this in the options, they are grayed out (as pictured) for some reason. I cannot re-add the cat carrier as a custom drop track either, evidently because it cannot be in two places at once.

**Comment by SacredDuckwhale** [comment]
Can it actually drop from *every* enemy in the zone, though? Wowhead data isn't very conclusive here, and Blizzard's journal entry can hardly be considered specific enough to be sure.

Currently, Rarity recognizes 13 NPCs while wowhead lists 19, of which a number have drop rates so low that it might as well be an error.

Either way, you can't edit the settings ingame because this item is part of the database that comes with the addon. I can change the entry to include the missing NPCs, if that helps?

**Comment by astradamus** [comment]
Why would we not consider the journal entry conclusive? Given how many of these rare pet drops were later extended to their entire zone (like the Azure Whelp in Winterspring), it seems far more parsimonious to assume that Word of God is correct here than to assume it is not?

**Comment by SacredDuckwhale** [comment]
It appears you're reading a whole lot into what I wrote that isn't really there, so apologies if I didn't express myself well. I have no stake/opinion in the matter. I'm merely questioning things because it's what I do, and I didn't assume anything either.

It's perfectly reasonable for me to wonder if they did in fact change this, and just as reasonable for you to provide the arguments you did. Just because I didn't change it right away doesn't mean I'm not considering it; I've looked at this issue for maybe a few minutes at most, so hopefully you don't take me wanting to look into it again as me disagreeing or trying to be "parsimonious".

Presenting this way might not be the best way to get people on your side, however, so I recommend being a bit careful with making assumptions :)

**Comment by SacredDuckwhale** [comment]
> EDIT: Either way, some kind of functionality change is in order. Either allowing the user to override database entry settings with their own local settings, or allowing custom entries to target the same items as fixed entries. Obviously the two of us disagree here on what's what, which means it should be up to the given user which way they want to go.

While this would be a neat feature, it would be difficult to implement due to how the addon was originally designed. In fact, like many other suggestions it's not feasible to implement this for me as I'd have to rewrite or refactor a large part of the code that the original author wrote first, and I simply don't have the time to do this :/

**Comment by astradamus** [comment]
I apologize, I think we have miscommunicated. "Parsimonious" is not a bad thing, I was referring to the concept of parsimony (i.e. Occam's Razor--the least convoluted solution is usually the correct one). That's something desirable, not offensive. Your questions were fair as was my disagreement, I was simply trying to argue that accepting that the change happened made more sense than denying that it did. I was disagreeing with your questions, not your right *to* question. You are correct in that we can't really know for sure, of course, unless someone is actually willing to kill >10k of each mob in the zone lol.

**Comment by SacredDuckwhale** [comment]
No worries. I might've misunderstood, as I'm not a native speaker and was also in a rush... as always, sigh.

I've changed it to be recognized as a zonewide drop in 0cde44c9351f946527f74884e3749d6233069246. Whether it really is, time will tell :)
