### ISSUE TITLE
Oh no!

### ISSUE THREAD

**Issue by Hellsz** [SacredDuckwhale/Rarity#214]
Hello, such an error pops up if you hover over the icon on the minimap or on the databar with the add-on
ty
_Rarity: Oh no! Something went horribly wrong. This is what happened:
Failed to add tooltip line for item 2 (invalid ID or the server didn't return any data)
If you didn't change anything that might've caused this, please report the error to the addon developer so it can be fixed :)_

**Comment by SacredDuckwhale** [comment]
I think this can only happen if there are invalid items in the Custom category, as the default items are all valid.

Please check the items you added; if there's something that says "failed to load" (or similar) you can probably get rid of the error by deleting it.

Otherwise, please try the latest alpha, in which the error message should be slightly more informative.

**Comment by Hellsz** [comment]
> I think this can only happen if there are invalid items in the Custom category, as the default items are all valid.
> 
> Please check the items you added; if there's something that says "failed to load" (or similar) you can probably get rid of the error by deleting it.
> 
> Otherwise, please try the latest alpha, in which the error message should be slightly more informative.

I think this method helped me, thanks a lot  <3
