### ISSUE TITLE
With the "hide items not in your zone" option checked, the tooltip doesn't show (?)

### ISSUE THREAD

**Issue by SacredDuckwhale** [SacredDuckwhale/Rarity#70]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/325)
> R681-release, yes I've restarted. In Stormsong at the moment, with "hide items not in your zone" checked, nothing shows when I hover over the minimap button, despite it detecting when I loot mobs that could drop Goldenmane's Reins.

No idea. Will have to investigate.

**Comment by adelpha** [comment]
Can confirm this behaviour. It's not every zone, but for **some** zones it seems that this:

`if currentZone == zoneValue.m then inMyZone = true end`

is not working.

For example:

In Isle of Quel'Danas `inMyZone` gets set correctly and Fossilized Raptor (archaeology mount) appears as an obtainable item when only displaying that zone.

If I zone into Magisters' Terrace it says there are no items to display. If I display the full list, Magisters' Terrace zonetext is grey, not green. Rarity just doesn't think I'm in that zone.

**Comment by godejord** [comment]
I think this is just a result of the wrong/missing UIMAPID for some zones.

In regards to the original issue from Wowace, he reported the issue on november 1. 2018. The mount in his example didn't have any coordinates attached to it at that point. This seems to have been added in 18f83694219a0d1096018df87ea4e70a526120e1 on the 7th of Nov 2020. I have verified that this setting works just fine with Goldenmane's Reins in Stormsong Valley now.

In the other example given, Magisters' Terrace, the issue is a more silly one. Magisters' Terrace is divided into two maps, and all three items referenced in the issue are linked with the second map. What this is means is when you first enter the instance, you spawn on the first map. The items are not linked to this map, so no items will show up in the GUI. As you progress past the second boss, you enter into the second map. Here all the three items are linked, and thus they will now appear in your GUI.

**Comment by SacredDuckwhale** [comment]
Yeah, with the new UiMapID system Blizzard introduced, every single map that has a separate map artwork is assigned a new UiMapID. This includes dungeons with multiple floors, but even basic things like the upper/lower level of the Vindicaar. They did provide a translation table that was supposedly intended to help translate from the old to the new system, but clearly that doesn't always work as expected.

In the case of Magister's Terrace, I'd simply suggest adding all the UiMapIDs of the dungeon to the list. It should hopefully display only one entry (since the names are identical, presumably) and still show regardless of the position inside the dungeon.

All the other missing map IDs should hopefully be added over time, or when the database is restructured (eventually....). I assume there's a lot of missing properties due to how loosely-enforced the layout is.

**Comment by godejord** [comment]
> In the case of Magister's Terrace, I'd simply suggest adding all the UiMapIDs of the dungeon to the list. It should hopefully display only one entry (since the names are identical, presumably) and still show regardless of the position inside the dungeon.
> 

Adding all the maps for the dungeon was my initial thought as well, and it does solve the issue with "hide items not in your zone". However, the zone names **do** appear multiple times in the GUI, so in this case it says "Magister's Terrace + 1" or just simply "Magister's Terrace, Magister's Terrace"

**Comment by SacredDuckwhale** [comment]
Indeed, that's somewhat unfortunate. I've tinkered around with the UI, trying to fix this display issue. Unfortunately there's a giant mountain of spaghetti code inside and I didn't manage to get it to work properly in a reasonable timeframe.

I guess that means it's shelved until there's been some major refactoring, as otherwise it's simply not worth the time trying to shoehorn it in.

**Comment by SacredDuckwhale** [comment]
Since this issue is about the missing UiMapIDs, I'll consider it "fixed" (oh well). There's no proper way to detect multiple subzones and combine them, and I'm not hacking it in because that'll just make everything worse.

If we can compile a list of affected dungeons, adding all their subzone mapIDs manually seems like a usable workaround until a proper fix can be implemented.

**Comment by SacredDuckwhale** [comment]
The IDs for Magister's Terrace have been added as of 17849513c524a1cb23ea40cce6540c2c4b464721 and 3c101319c4943a847bb3a84750029706e752097b.
